### ISSUE TITLE
Use Pycord rather than DiscordTogether

### ISSUE THREAD

**Issue by OmLanke** [DTS-11/PizzaHat#27]
**Is your feature request related to a problem? Please describe.**
The bot currently uses DiscordTogether for voice channel embedded activities. The same functionality in built-in in pycord. Using another 3rd party library is not needed

**Describe the solution you'd like**
Use the `create_activity_invite` method on a voice channel. 
Ex- `link = await ctx.author.voice.channel.create_activity_invite(discord.EmbeddedActivity.watch_together)`

**Describe alternatives you've considered**

**Additional context**
I can create a pr if you want

**Comment by DTS-11** [comment]
I didn't know that existed.. and also since discord.py is back in development, I might switch to it in the future, when they release a stable version... I'm slightly biased towards dpy than other forks.

**Comment by DTS-11** [comment]
I'm closing this issue, if you want to talk more about this, consider joining our server or we'll discuss this in discussions

**Comment by DTS-11** [comment]
Discord activities has been rolled out to almost (if not every) clients. I've also removed the cog from the bot.
Feel free to contribute to the project regarding other features!
